import {
  Activity,
  Archive,
  ArrowDownToLine,
  ArrowUpFromLine,
  Atom,
  BarChart3,
  Beaker,
  Box,
  CircleHelp,
  CircleUserRound,
  ClipboardList,
  CloudDownload,
  Command,
  Copy,
  Download,
  Eye,
  EyeOff,
  FilePlus2,
  FileUp,
  FolderOpen,
  Gauge,
  Grid2X2,
  Hand,
  HelpCircle,
  Layers3,
  LoaderCircle,
  LockKeyhole,
  Menu,
  Moon,
  Minus,
  MousePointer2,
  Move3d,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  PencilRuler,
  Plus,
  Redo2,
  Rotate3d,
  Ruler,
  Save,
  Settings,
  Shapes,
  SlidersHorizontal,
  Sparkles,
  Square,
  Sun,
  Target,
  Trash2,
  Undo2,
  Upload,
  Waves,
  X,
  ZoomIn,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const icons: Record<string, LucideIcon> = {
  activity: Activity,
  archive: Archive,
  arrowDown: ArrowDownToLine,
  arrowUp: ArrowUpFromLine,
  atom: Atom,
  bars: BarChart3,
  beaker: Beaker,
  box: Box,
  circleHelp: CircleHelp,
  circleUser: CircleUserRound,
  clipboard: ClipboardList,
  cloudDownload: CloudDownload,
  command: Command,
  copy: Copy,
  download: Download,
  eye: Eye,
  eyeOff: EyeOff,
  filePlus: FilePlus2,
  fileUp: FileUp,
  folder: FolderOpen,
  gauge: Gauge,
  grid: Grid2X2,
  hand: Hand,
  help: HelpCircle,
  layers: Layers3,
  loader: LoaderCircle,
  lock: LockKeyhole,
  menu: Menu,
  moon: Moon,
  minus: Minus,
  pointer: MousePointer2,
  move3d: Move3d,
  panelLeftClose: PanelLeftClose,
  panelLeftOpen: PanelLeftOpen,
  panelRightClose: PanelRightClose,
  panelRightOpen: PanelRightOpen,
  pencil: PencilRuler,
  plus: Plus,
  redo: Redo2,
  rotate: Rotate3d,
  ruler: Ruler,
  save: Save,
  settings: Settings,
  shapes: Shapes,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  square: Square,
  sun: Sun,
  target: Target,
  trash: Trash2,
  undo: Undo2,
  upload: Upload,
  waves: Waves,
  x: X,
  zoom: ZoomIn,
};

export type IconName = keyof typeof icons;

export const Icon = ({ name, size = 18, strokeWidth = 1.7 }: { name: IconName; size?: number; strokeWidth?: number }) => {
  const Component = icons[name];
  return <Component aria-hidden="true" size={size} strokeWidth={strokeWidth} />;
};
