import { useEffect, useState } from "react";
import type { StructureLoadResult } from "@molecular/contracts";
import type { ActionId } from "../domain/registry";
import { labelPlanForState, serializeSafeLabelExpression } from "../interaction/labels";
import { BACKGROUND_PRESETS, COLOR_SCHEMES, styleProfileFor, type BackgroundPreset, type CameraState, type ColorMode, type RenderProjection, type RepresentationParameters, type RepresentationStyle } from "../rendering/renderProjection";
import { colorRegistry } from "../rendering/colorRegistry";
import { representationCapabilitiesForTarget, representationCapabilityFor, STYLE_DEFINITIONS, styleLabel } from "../rendering/styleProfiles";
import { Icon } from "./Icon";

type DisplayCategory = "protein" | "ligand" | "water" | "ions" | "other";
type InspectorPanelProps = {
  collapsed: boolean;
  onToggle: () => void;
  onAction: (actionId: ActionId) => void;
  structure: StructureLoadResult | null;
  projection: RenderProjection;
  onStyleChange: (style: RepresentationStyle) => void;
  onTargetStyle: (category: DisplayCategory, style: RepresentationStyle) => void;
  targetStyles: Record<DisplayCategory, RepresentationStyle>;
  onColorMode: (mode: ColorMode) => void;
  onNamedColor: (colorId: string) => void;
  onCustomColor: (hex: string) => void;
  onComponentColor: (category: DisplayCategory, mode: "inherit" | "element" | "chain" | "custom", customHex?: string) => void;
  onBackgroundPreset: (preset: BackgroundPreset) => void;
  onBackgroundColor: (hex: string) => void;
  onLabelMode: (mode: import("../interaction/labels").LabelMode) => void;
  onLabelExpression: (expression: string) => boolean;
  onCameraProjection: (projection: CameraState["projectionMode"]) => void;
  onCameraSettings: (camera: Partial<CameraState>) => void;
  onRepresentationSettings: (settings: Partial<RepresentationParameters>) => void;
};

const categoryLabels: Array<[DisplayCategory, string, "cyan" | "orange" | "blue" | "purple" | "slate"]> = [["protein", "Protein", "blue"], ["ligand", "Ligand", "purple"], ["water", "Water", "cyan"], ["ions", "Ions", "orange"], ["other", "Other", "slate"]];
const categoryVisibilityAction: Record<DisplayCategory, ActionId> = { protein: "REPRESENTATION.TOGGLE_PROTEIN", ligand: "REPRESENTATION.TOGGLE_LIGAND", water: "REPRESENTATION.TOGGLE_WATER", ions: "REPRESENTATION.TOGGLE_IONS", other: "REPRESENTATION.TOGGLE_OTHER" };
const numberValue = (value: number): string => Number.isFinite(value) ? String(value) : "";
const selectValueForStyle = (style: RepresentationStyle): string => styleProfileFor(style) === "stick" ? "sticks" : styleProfileFor(style);
const hasActiveStyle = (styles: Set<RepresentationStyle>, values: readonly RepresentationStyle[]): boolean => values.some((value) => styles.has(value));

export const InspectorPanel = ({ collapsed, onToggle, onAction, structure, projection, onStyleChange, onTargetStyle, targetStyles, onColorMode, onNamedColor, onCustomColor, onComponentColor, onBackgroundPreset, onBackgroundColor, onLabelMode, onLabelExpression, onCameraProjection, onCameraSettings, onRepresentationSettings }: InspectorPanelProps) => {
  const savedLabelExpression = projection.labels.expression ? serializeSafeLabelExpression(projection.labels.expression) : "{name} {resn}{resi}";
  const [labelExpressionDraft, setLabelExpressionDraft] = useState(savedLabelExpression);
  useEffect(() => setLabelExpressionDraft(savedLabelExpression), [savedLabelExpression]);
  if (collapsed) return <button className="collapsed-panel-tab collapsed-panel-tab--right" onClick={onToggle} aria-label="Expand Projection & Display panel"><Icon name="panelRightOpen" size={17} /></button>;
  const currentCapability = representationCapabilityFor(projection.representation, structure?.structure ?? null);
  const selectedStyleValue = selectValueForStyle(projection.representation);
  const labelAtoms = structure?.structure.atoms.filter((atom) => atom.isPolymer ? projection.showProtein : atom.isLigand ? projection.showLigand : atom.isWater ? projection.showWater : atom.isIon ? projection.showIons : projection.showOther) ?? [];
  const labelPlan = labelPlanForState(projection.labels, labelAtoms);
  const styleOptions = STYLE_DEFINITIONS.map((definition) => representationCapabilityFor(definition.id, structure?.structure ?? null));
  const activeStyles = new Set<RepresentationStyle>([projection.representation, ...Object.values(targetStyles)]);
  const showLines = hasActiveStyle(activeStyles, ["lines", "line"]);
  const showSticks = hasActiveStyle(activeStyles, ["sticks", "stick", "ball-and-stick", "licorice"]);
  const showSpheres = hasActiveStyle(activeStyles, ["spheres", "space-filling", "ball-and-stick", "nonbonded-spheres"]);
  const showCartoon = hasActiveStyle(activeStyles, ["cartoon", "ribbon", "trace", "putty"]);
  const showSurface = hasActiveStyle(activeStyles, ["van-der-waals-surface", "solvent-accessible-surface", "solvent-excluded-surface"]);
  const showMesh = hasActiveStyle(activeStyles, ["mesh"]);
  const showDots = hasActiveStyle(activeStyles, ["dots", "dot-surface"]);
  const showPutty = hasActiveStyle(activeStyles, ["putty"]);
  const toggleRow = (label: string, enabled: boolean, tone: "cyan" | "orange" | "blue" | "purple" | "slate") => <button className="display-row display-row--button" onClick={() => onAction(categoryVisibilityAction[label.toLowerCase() as DisplayCategory])} aria-label={`Toggle ${label}`} aria-pressed={enabled} data-action-id={categoryVisibilityAction[label.toLowerCase() as DisplayCategory]} disabled={!structure}><span>{label}</span><span className={`switch switch--${tone} ${enabled ? "switch--on" : ""}`} role="switch" aria-checked={enabled}><span /></span></button>;
  return (
    <aside className="side-column side-column--right" aria-label="Projection & Display panel" data-testid="projection-display-panel">
      <section className="panel-card display-card projection-display-card">
        <div className="panel-heading"><div><span className="eyebrow">PRESENTATION</span><h2>Projection &amp; Display</h2></div><div className="panel-actions"><span className="capability-tag">AUTHORITATIVE</span><button className="icon-button" onClick={onToggle} aria-label="Collapse Projection & Display panel"><Icon name="panelRightClose" size={16} /></button></div></div>
        <div className="display-scroll">
          <details open><summary>Representation</summary><div className="details-body"><label className="display-row"><span>Global style</span><select aria-label="Style" value={selectedStyleValue} onChange={(event) => onStyleChange(event.target.value as RepresentationStyle)}>{styleOptions.map((definition) => <option key={definition.id} value={definition.id === "stick" ? "sticks" : definition.id} disabled={!definition.maySelect} data-capability-state={definition.capability} data-representation-status={definition.status}>{definition.label}</option>)}</select></label><div className="display-capability" data-style-profile={styleProfileFor(projection.representation)} data-capability-status={currentCapability.status}>{styleLabel(projection.representation)} · {currentCapability.status.replaceAll("_", " ")} · {currentCapability.capability.replaceAll("_", " ")}</div>{currentCapability.diagnostic && <div className="presentation-diagnostic" role="alert">{currentCapability.diagnostic}</div>}{categoryLabels.map(([category, label]) => { const options = representationCapabilitiesForTarget(category, structure?.structure ?? null); return <label className="display-row display-row--sub" key={category}><span>{label}</span><select aria-label={`${label} representation`} value={selectValueForStyle(targetStyles[category])} onChange={(event) => onTargetStyle(category, event.target.value as RepresentationStyle)}>{options.map((definition) => <option key={definition.id} value={definition.id === "stick" ? "sticks" : definition.id} disabled={!definition.maySelect} data-capability-state={definition.capability} data-representation-status={definition.status}>{definition.label}</option>)}</select></label>; })}</div></details>
          <details open><summary>Color</summary><div className="details-body"><label className="display-row"><span>Scheme</span><select aria-label="Color mode" value={projection.color.mode} onChange={(event) => onColorMode(event.target.value as ColorMode)}>{COLOR_SCHEMES.map((scheme) => <option key={scheme.id} value={scheme.id}>{scheme.name}</option>)}</select></label>{projection.color.mode === "named" && <label className="display-row display-row--sub"><span>Named</span><select aria-label="Named color" value={projection.color.colorId ?? "pymol:marine"} onChange={(event) => onNamedColor(event.target.value)}>{colorRegistry.list().map((definition) => <option key={definition.colorId} value={definition.colorId}>{definition.canonicalName}</option>)}</select></label>}{projection.color.mode === "custom" && <label className="display-row display-row--sub"><span>HEX</span><input aria-label="Custom color" type="color" value={projection.color.customHex ?? "#d7e0ea"} onChange={(event) => onCustomColor(event.target.value)} /></label>}<div className="display-capability">Component overrides · inherit from global unless explicitly set</div>{categoryLabels.map(([category, label]) => { const override = projection.color.componentColors[category]; const mode = override?.mode ?? "inherit"; return <div className="display-row display-row--sub" key={`${category}-color`}><span>{label}</span><select aria-label={`${label} color`} value={mode} onChange={(event) => onComponentColor(category, event.target.value as "inherit" | "element" | "chain" | "custom", override?.customHex ?? undefined)}><option value="inherit">Inherit</option><option value="element">By Element</option><option value="chain">By Chain</option><option value="custom">Custom</option></select>{mode === "custom" && <input aria-label={`${label} custom color`} type="color" value={override?.customHex ?? "#d7e0ea"} onChange={(event) => onComponentColor(category, "custom", event.target.value)} />}</div>; })}{projection.colorDiagnostic && <div className="presentation-diagnostic" role="alert">{projection.colorDiagnostic}</div>}</div></details>
          <details open><summary>Visibility</summary><div className="details-body">{categoryLabels.map(([category, label, tone]) => <div key={category}>{toggleRow(label, projection[`show${label}` as "showProtein" | "showLigand" | "showWater" | "showIons" | "showOther"], tone)}</div>)}</div></details>
          <details open><summary>View</summary><div className="details-body"><label className="display-row"><span>Projection</span><select aria-label="Projection mode" value={projection.camera.projectionMode} onChange={(event) => onCameraProjection(event.target.value as CameraState["projectionMode"])}><option value="perspective">Perspective</option><option value="orthographic">Orthographic</option></select></label><div className="button-grid"><button type="button" onClick={() => onAction("VIEW.FIT")}>Fit</button><button type="button" onClick={() => onAction("VIEW.CENTER")}>Center</button><button type="button" onClick={() => onAction("VIEW.ORIENT")}>Orient</button><button type="button" onClick={() => onAction("VIEW.RESET")}>Reset</button></div></div></details>
          <details open><summary>Background</summary><div className="details-body"><label className="display-row"><span>Preset</span><select aria-label="Background preset" value={projection.background.preset} onChange={(event) => onBackgroundPreset(event.target.value as BackgroundPreset)}>{BACKGROUND_PRESETS.map((preset) => <option key={preset} value={preset}>{preset}</option>)}</select></label>{projection.background.preset === "Custom" && <label className="display-row display-row--sub"><span>HEX</span><input aria-label="Custom background color" type="color" value={projection.background.color} onChange={(event) => onBackgroundColor(event.target.value)} /></label>}</div></details>
          <details><summary>Labels</summary><div className="details-body"><label className="display-row"><span>Preset</span><select aria-label="Label mode" value={projection.labels.mode} onChange={(event) => onLabelMode(event.target.value as import("../interaction/labels").LabelMode)}><option value="off">Off</option><option value="atom-name">Atom Name</option><option value="residue">Residue</option><option value="residue-number">Residue + Number</option><option value="chain">Chain</option><option value="custom">Custom</option></select></label>{projection.labels.mode === "custom" && <label className="display-row display-row--sub"><span>Expression</span><input aria-label="Label expression" value={labelExpressionDraft} onChange={(event) => setLabelExpressionDraft(event.target.value)} onBlur={(event) => { if (!onLabelExpression(event.target.value)) setLabelExpressionDraft(savedLabelExpression); }} /></label>}{labelPlan.diagnostic && <div className="presentation-diagnostic" role="alert">{labelPlan.diagnostic}</div>}{projection.labels.mode !== "off" && !labelPlan.diagnostic && <div className="display-capability" data-label-cardinality={labelPlan.labelCount}>{labelPlan.labelCount} label{labelPlan.labelCount === 1 ? "" : "s"} from canonical {projection.labels.mode === "chain" ? "chain" : projection.labels.mode.includes("residue") ? "residue" : "atom"} target{labelPlan.labelCount === 1 ? "" : "s"}</div>}</div></details>
          <details><summary>Representation Settings</summary><div className="details-body">
            {showSticks && <label className="display-range"><span>Stick radius <output>{projection.representationState.parameters.stickRadius.toFixed(2)}</output></span><input aria-label="Stick radius" type="range" min="0.05" max="0.5" step="0.01" value={projection.representationState.parameters.stickRadius} onChange={(event) => onRepresentationSettings({ stickRadius: Number(event.target.value) })} /></label>}
            {showSpheres && <label className="display-range"><span>Sphere scale <output>{projection.representationState.parameters.sphereScale.toFixed(2)}</output></span><input aria-label="Sphere scale" type="range" min="0.25" max="1.5" step="0.05" value={projection.representationState.parameters.sphereScale} onChange={(event) => onRepresentationSettings({ sphereScale: Number(event.target.value) })} /></label>}
            {showLines && <label className="display-range"><span>Line width <output>{projection.representationState.parameters.lineWidth.toFixed(1)}</output></span><input aria-label="Line width" type="range" min="0.5" max="4" step="0.5" value={projection.representationState.parameters.lineWidth} onChange={(event) => onRepresentationSettings({ lineWidth: Number(event.target.value) })} /></label>}
            {showCartoon && <label className="display-range"><span>Cartoon thickness <output>{projection.representationState.parameters.cartoonThickness.toFixed(2)}</output></span><input aria-label="Cartoon thickness" type="range" min="0.3" max="1.3" step="0.05" value={projection.representationState.parameters.cartoonThickness} onChange={(event) => onRepresentationSettings({ cartoonThickness: Number(event.target.value) })} /></label>}
            {showLines && <label className="display-range"><span>Line opacity <output>{projection.representationState.parameters.lineOpacity.toFixed(2)}</output></span><input aria-label="Line opacity" type="range" min="0" max="1" step="0.05" value={projection.representationState.parameters.lineOpacity} onChange={(event) => onRepresentationSettings({ lineOpacity: Number(event.target.value) })} /></label>}
            {showSticks && <label className="display-range"><span>Stick opacity <output>{projection.representationState.parameters.stickOpacity.toFixed(2)}</output></span><input aria-label="Stick opacity" type="range" min="0" max="1" step="0.05" value={projection.representationState.parameters.stickOpacity} onChange={(event) => onRepresentationSettings({ stickOpacity: Number(event.target.value) })} /></label>}
            {showSpheres && <label className="display-range"><span>Sphere opacity <output>{projection.representationState.parameters.sphereOpacity.toFixed(2)}</output></span><input aria-label="Sphere opacity" type="range" min="0" max="1" step="0.05" value={projection.representationState.parameters.sphereOpacity} onChange={(event) => onRepresentationSettings({ sphereOpacity: Number(event.target.value) })} /></label>}
            {showCartoon && <label className="display-range"><span>Cartoon opacity <output>{projection.representationState.parameters.cartoonOpacity.toFixed(2)}</output></span><input aria-label="Cartoon opacity" type="range" min="0" max="1" step="0.05" value={projection.representationState.parameters.cartoonOpacity} onChange={(event) => onRepresentationSettings({ cartoonOpacity: Number(event.target.value) })} /></label>}
            {hasActiveStyle(activeStyles, ["ribbon"]) && <label className="display-range"><span>Ribbon opacity <output>{projection.representationState.parameters.ribbonOpacity.toFixed(2)}</output></span><input aria-label="Ribbon opacity" type="range" min="0" max="1" step="0.05" value={projection.representationState.parameters.ribbonOpacity} onChange={(event) => onRepresentationSettings({ ribbonOpacity: Number(event.target.value) })} /></label>}
            {showSurface && <label className="display-range"><span>Surface opacity <output>{projection.representationState.parameters.surfaceOpacity.toFixed(2)}</output></span><input aria-label="Surface opacity" type="range" min="0" max="1" step="0.05" value={projection.representationState.parameters.surfaceOpacity} onChange={(event) => onRepresentationSettings({ surfaceOpacity: Number(event.target.value) })} /></label>}
            {showMesh && <label className="display-range"><span>Mesh width <output>{projection.representationState.parameters.meshWidth.toFixed(1)}</output></span><input aria-label="Mesh width" type="range" min="0.5" max="4" step="0.5" value={projection.representationState.parameters.meshWidth} onChange={(event) => onRepresentationSettings({ meshWidth: Number(event.target.value) })} /></label>}
            {showMesh && <label className="display-range"><span>Mesh opacity <output>{projection.representationState.parameters.meshOpacity.toFixed(2)}</output></span><input aria-label="Mesh opacity" type="range" min="0" max="1" step="0.05" value={projection.representationState.parameters.meshOpacity} onChange={(event) => onRepresentationSettings({ meshOpacity: Number(event.target.value) })} /></label>}
            {showDots && <label className="display-range"><span>Dot opacity <output>{projection.representationState.parameters.dotOpacity.toFixed(2)}</output></span><input aria-label="Dot opacity" type="range" min="0" max="1" step="0.05" value={projection.representationState.parameters.dotOpacity} onChange={(event) => onRepresentationSettings({ dotOpacity: Number(event.target.value) })} /></label>}
            {hasActiveStyle(activeStyles, ["dot-surface"]) && <label className="display-range"><span>Surface probe radius <output>{projection.representationState.parameters.surfaceProbeRadius.toFixed(2)} Å</output></span><input aria-label="Surface probe radius" type="range" min="0" max="3" step="0.1" value={projection.representationState.parameters.surfaceProbeRadius} onChange={(event) => onRepresentationSettings({ surfaceProbeRadius: Number(event.target.value) })} /></label>}
            {showDots && <label className="display-range"><span>Surface quality <output>{projection.representationState.parameters.surfaceQuality.toFixed(2)}</output></span><input aria-label="Surface quality" type="range" min="0.1" max="1" step="0.1" value={projection.representationState.parameters.surfaceQuality} onChange={(event) => onRepresentationSettings({ surfaceQuality: Number(event.target.value) })} /></label>}
            {showDots && <label className="display-range"><span>Dot density <output>{projection.representationState.parameters.dotDensity}</output></span><input aria-label="Dot density" type="range" min="6" max="36" step="1" value={projection.representationState.parameters.dotDensity} onChange={(event) => onRepresentationSettings({ dotDensity: Number(event.target.value) })} /></label>}
            {showPutty && <label className="display-range"><span>Putty minimum radius <output>{projection.representationState.parameters.puttyMinRadius.toFixed(2)}</output></span><input aria-label="Putty minimum radius" type="range" min="0.05" max="0.8" step="0.01" value={projection.representationState.parameters.puttyMinRadius} onChange={(event) => onRepresentationSettings({ puttyMinRadius: Number(event.target.value) })} /></label>}
            {showPutty && <label className="display-range"><span>Putty maximum radius <output>{projection.representationState.parameters.puttyMaxRadius.toFixed(2)}</output></span><input aria-label="Putty maximum radius" type="range" min="0.2" max="1.5" step="0.01" value={projection.representationState.parameters.puttyMaxRadius} onChange={(event) => onRepresentationSettings({ puttyMaxRadius: Number(event.target.value) })} /></label>}
          </div></details>
          <details><summary>Advanced Display</summary><div className="details-body"><div className="display-capability">Clipping · {projection.camera.clippingMode.toUpperCase()}</div><label className="display-range"><span>FOV <output>{projection.camera.fov.toFixed(0)}°</output></span><input aria-label="Camera FOV" type="range" min="5" max="90" step="1" value={projection.camera.fov} onChange={(event) => onCameraSettings({ fov: Number(event.target.value) })} /></label><label className="display-range"><span>Near clip <output>{numberValue(projection.camera.nearClip)}</output></span><input aria-label="Near clip" type="number" min="0.01" step="0.01" value={projection.camera.nearClip} onChange={(event) => onCameraSettings({ nearClip: Math.max(0.01, Number(event.target.value)) })} /></label><label className="display-range"><span>Far clip <output>{numberValue(projection.camera.farClip)}</output></span><input aria-label="Far clip" type="number" min="1" step="1" value={projection.camera.farClip} onChange={(event) => onCameraSettings({ farClip: Math.max(projection.camera.nearClip + 1, Number(event.target.value)) })} /></label><button type="button" className="reset-view" onClick={() => onCameraSettings({ clippingMode: "auto" })}>Reset clipping to Auto</button></div></details>
        </div>
      </section>
    </aside>
  );
};
