import type { CanonicalAtom, StructureLoadResult } from "@molecular/contracts";
import type { ActionId } from "../domain/registry";
import type { MeasurementKind, MeasurementObject } from "../interaction/measurements";
import { BACKGROUND_PRESETS, COLOR_SCHEMES, type BackgroundPreset, type CameraState, type ColorMode, type RenderProjection, type RepresentationParameters, type RepresentationStyle } from "../rendering/renderProjection";
import { colorRegistry } from "../rendering/colorRegistry";
import { styleLabel, STYLE_DEFINITIONS } from "../rendering/styleProfiles";
import { styleProfileFor } from "../rendering/renderProjection";
import type { LabelMode } from "../interaction/labels";
import { formatMeasurement } from "../interaction/measurements";
import { Icon } from "./Icon";

type DisplayCategory = "protein" | "ligand" | "water" | "ions" | "other";
type InspectorPanelProps = {
  collapsed: boolean;
  onToggle: () => void;
  onAction: (actionId: ActionId) => void;
  structure: StructureLoadResult | null;
  projection: RenderProjection;
  onStyleChange: (style: RepresentationStyle) => void;
  onTargetStyle: (category: DisplayCategory, style: RepresentationStyle) => void;
  targetStyles: Record<DisplayCategory, RepresentationStyle>;
  onColorMode: (mode: ColorMode) => void;
  onNamedColor: (colorId: string) => void;
  onCustomColor: (hex: string) => void;
  onBackgroundPreset: (preset: BackgroundPreset) => void;
  onBackgroundColor: (hex: string) => void;
  selectedAtom: CanonicalAtom | null;
  onLabelMode: (mode: LabelMode) => void;
  onLabelExpression: (expression: string) => void;
  onCameraProjection: (projection: CameraState["projectionMode"]) => void;
  onCameraSettings: (camera: Partial<CameraState>) => void;
  onRepresentationSettings: (settings: Partial<RepresentationParameters>) => void;
  measurementMode: MeasurementKind | null;
  measurementSlots: readonly string[];
  measurements: readonly MeasurementObject[];
  onMeasurementMode: (kind: MeasurementKind | null) => void;
  onMeasurementVisibility: (id: string, visible: boolean) => void;
  onMeasurementDelete: (id: string) => void;
  onMeasurementClear: () => void;
};

const styleOptions = STYLE_DEFINITIONS.filter((definition) => definition.id !== "licorice");
const toggleAction = (label: string): ActionId => ({ Protein: "REPRESENTATION.TOGGLE_PROTEIN", Ligand: "REPRESENTATION.TOGGLE_LIGAND", Water: "REPRESENTATION.TOGGLE_WATER", Ions: "REPRESENTATION.TOGGLE_IONS", Other: "REPRESENTATION.TOGGLE_OTHER" }[label] as ActionId);
const categoryLabels: Array<[DisplayCategory, string, "cyan" | "orange" | "blue" | "purple" | "slate"]> = [["protein", "Protein", "blue"], ["ligand", "Ligand", "purple"], ["water", "Water", "cyan"], ["ions", "Ions", "orange"], ["other", "Other", "slate"]];
const styleTargetOptions: Array<[RepresentationStyle, string]> = [["cartoon", "Cartoon"], ["ribbon", "Ribbon"], ["sticks", "Sticks"], ["lines", "Lines"], ["spheres", "Spheres"], ["ball-and-stick", "Ball & Stick"], ["nonbonded-crosses", "Non-bonded"]];

const numberValue = (value: number): string => Number.isFinite(value) ? String(value) : "";

export const InspectorPanel = ({ collapsed, onToggle, onAction, structure, projection, onStyleChange, onTargetStyle, targetStyles, onColorMode, onNamedColor, onCustomColor, onBackgroundPreset, onBackgroundColor, selectedAtom, onLabelMode, onLabelExpression, onCameraProjection, onCameraSettings, onRepresentationSettings, measurementMode, measurementSlots, measurements, onMeasurementMode, onMeasurementVisibility, onMeasurementDelete, onMeasurementClear }: InspectorPanelProps) => {
  if (collapsed) return <button className="collapsed-panel-tab collapsed-panel-tab--right" onClick={onToggle} aria-label="Expand inspector panel"><Icon name="panelRightOpen" size={17} /></button>;
  const toggleRow = (label: string, enabled: boolean, tone: "cyan" | "orange" | "blue" | "purple" | "slate") => { const actionId = toggleAction(label); return <button className="display-row display-row--button" onClick={() => onAction(actionId)} aria-label={`Toggle ${label}`} aria-pressed={enabled} data-action-id={actionId} disabled={!structure}><span>{label}</span><span className={`switch switch--${tone} ${enabled ? "switch--on" : ""}`} role="switch" aria-checked={enabled}><span /></span></button>; };
  const selectedStyle = styleOptions.some((definition) => definition.id === projection.representation) ? projection.representation : styleProfileFor(projection.representation);
  const selectedIds = projection.interaction.selectedAtomIds;
  const atom = selectedAtom;
  const activeMeasurement = (kind: MeasurementKind) => measurementMode === kind;
  return (
    <aside className="side-column side-column--right" aria-label="Selection inspector and display panel">
      <section className="panel-card inspector-card">
        <div className="panel-heading"><div><span className="eyebrow">CONTEXT</span><h2>{atom ? "Molecular Inspector" : "Selection Inspector"}</h2></div><div className="panel-actions"><button className="icon-button" onClick={onToggle} aria-label="Collapse inspector panel"><Icon name="panelRightClose" size={16} /></button></div></div>
        <div className="inspector-selection"><span>Selection</span><span className="selection-chip">{selectedIds.length ? `${selectedIds.length} atom${selectedIds.length === 1 ? "" : "s"}` : "none"}</span></div>
        <div className="selection-meta">{atom ? `${atom.atomName} · ${atom.residueName} ${atom.residueNumber} · Chain ${atom.chain}` : `${selectedIds.length} atoms`}</div>
        <div className="inspector-divider" />
        {atom ? <div className="atom-inspector" data-testid="molecular-inspector"><div className="atom-inspector-title"><strong>{atom.atomName}</strong><span>{atom.residueName} {atom.residueNumber} · Chain {atom.chain}</span></div><div className="atom-property-grid"><span>Element</span><strong>{atom.element}</strong><span>Coordinates</span><strong>{atom.x.toFixed(3)}, {atom.y.toFixed(3)}, {atom.z.toFixed(3)} Å</strong><span>Occupancy</span><strong>{atom.occupancy == null ? "—" : atom.occupancy.toFixed(2)}</strong><span>B-factor</span><strong>{atom.bFactor == null ? "—" : atom.bFactor.toFixed(2)}</strong><span>Formal charge</span><strong>{atom.formalCharge == null ? "—" : atom.formalCharge}</strong><span>Object/model</span><strong>{structure?.structure.name ?? "—"}</strong></div><div className="inspector-inline-actions"><button type="button" onClick={() => onAction("CANVAS.SELECT")}>Select</button><button type="button" onClick={() => onMeasurementMode("DISTANCE")}>Measure</button></div></div> : <div className="empty-inspector"><span className="empty-orbit"><Icon name="target" size={22} /></span><strong>No selection</strong><span>Click an atom in Select mode to inspect canonical molecular data.</span></div>}
      </section>
      <section className="panel-card display-card projection-display-card">
        <div className="panel-heading"><div><span className="eyebrow">PRESENTATION</span><h2>Projection &amp; Display</h2></div><Icon name="sliders" size={16} /></div>
        <div className="display-scroll">
          <details open><summary>Representation</summary><div className="details-body"><label className="display-row"><span>Global style</span><select aria-label="Style" value={selectedStyle} onChange={(event) => onStyleChange(event.target.value as RepresentationStyle)}>{styleOptions.map((definition) => <option key={definition.id} value={definition.id} data-capability-state={definition.capability}>{definition.label}</option>)}</select></label><div className="display-capability" data-style-profile={styleProfileFor(projection.representation)}>{styleLabel(styleProfileFor(projection.representation))} · {STYLE_DEFINITIONS.find((definition) => definition.id === styleProfileFor(projection.representation))?.capability.replaceAll("_", " ")}</div>{categoryLabels.map(([category, label]) => <label className="display-row display-row--sub" key={category}><span>{label}</span><select aria-label={`${label} representation`} value={targetStyles[category]} onChange={(event) => onTargetStyle(category, event.target.value as RepresentationStyle)}>{styleTargetOptions.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label>)}</div></details>
          <details open><summary>Color</summary><div className="details-body"><label className="display-row"><span>Scheme</span><select aria-label="Color mode" value={projection.color.mode} onChange={(event) => onColorMode(event.target.value as ColorMode)}>{COLOR_SCHEMES.map((scheme) => <option key={scheme.id} value={scheme.id}>{scheme.name}</option>)}</select></label>{projection.color.mode === "named" && <label className="display-row display-row--sub"><span>Named</span><select aria-label="Named color" value={projection.color.colorId ?? "pymol:marine"} onChange={(event) => onNamedColor(event.target.value)}>{colorRegistry.list().map((definition) => <option key={definition.colorId} value={definition.colorId}>{definition.canonicalName}</option>)}</select></label>}{projection.color.mode === "custom" && <label className="display-row display-row--sub"><span>HEX</span><input aria-label="Custom color" type="color" value={projection.color.customHex ?? "#d7e0ea"} onChange={(event) => onCustomColor(event.target.value)} /></label>}{projection.colorDiagnostic && <div className="presentation-diagnostic" role="alert">{projection.colorDiagnostic}</div>}</div></details>
          <details open><summary>Visibility</summary><div className="details-body">{categoryLabels.map(([category, label, tone]) => <div key={category}>{toggleRow(label, projection[`show${label}` as "showProtein" | "showLigand" | "showWater" | "showIons" | "showOther"], tone)}</div>)}</div></details>
          <details open><summary>View</summary><div className="details-body"><label className="display-row"><span>Projection</span><select aria-label="Projection mode" value={projection.camera.projectionMode} onChange={(event) => onCameraProjection(event.target.value as CameraState["projectionMode"])}><option value="perspective">Perspective</option><option value="orthographic">Orthographic</option></select></label><div className="button-grid"><button type="button" onClick={() => onAction("VIEW.FIT")}>Fit</button><button type="button" onClick={() => onAction("VIEW.CENTER")}>Center</button><button type="button" onClick={() => onAction("VIEW.ORIENT")}>Orient</button><button type="button" onClick={() => onAction("VIEW.RESET")}>Reset</button></div></div></details>
          <details open><summary>Background</summary><div className="details-body"><label className="display-row"><span>Preset</span><select aria-label="Background preset" value={projection.background.preset} onChange={(event) => onBackgroundPreset(event.target.value as BackgroundPreset)}>{BACKGROUND_PRESETS.map((preset) => <option key={preset} value={preset}>{preset}</option>)}</select></label>{projection.background.preset === "Custom" && <label className="display-row display-row--sub"><span>HEX</span><input aria-label="Custom background color" type="color" value={projection.background.color} onChange={(event) => onBackgroundColor(event.target.value)} /></label>}</div></details>
          <details><summary>Labels</summary><div className="details-body"><label className="display-row"><span>Preset</span><select aria-label="Label mode" value={projection.labels.mode} onChange={(event) => onLabelMode(event.target.value as LabelMode)}><option value="off">Off</option><option value="atom-name">Atom Name</option><option value="residue">Residue</option><option value="residue-number">Residue + Number</option><option value="chain">Chain</option><option value="custom">Custom</option></select></label>{projection.labels.mode === "custom" && <label className="display-row display-row--sub"><span>Expression</span><input aria-label="Label expression" defaultValue="{name} {resn}{resi}" onBlur={(event) => onLabelExpression(event.target.value)} /></label>}</div></details>
          <details><summary>Representation Settings</summary><div className="details-body"><label className="display-range"><span>Stick radius <output>{projection.representationState.parameters.stickRadius.toFixed(2)}</output></span><input aria-label="Stick radius" type="range" min="0.05" max="0.5" step="0.01" value={projection.representationState.parameters.stickRadius} onChange={(event) => onRepresentationSettings({ stickRadius: Number(event.target.value) })} /></label><label className="display-range"><span>Sphere scale <output>{projection.representationState.parameters.sphereScale.toFixed(2)}</output></span><input aria-label="Sphere scale" type="range" min="0.25" max="1.5" step="0.05" value={projection.representationState.parameters.sphereScale} onChange={(event) => onRepresentationSettings({ sphereScale: Number(event.target.value) })} /></label><label className="display-range"><span>Line width <output>{projection.representationState.parameters.lineWidth.toFixed(1)}</output></span><input aria-label="Line width" type="range" min="0.5" max="4" step="0.5" value={projection.representationState.parameters.lineWidth} onChange={(event) => onRepresentationSettings({ lineWidth: Number(event.target.value) })} /></label><label className="display-range"><span>Cartoon thickness <output>{projection.representationState.parameters.cartoonThickness.toFixed(2)}</output></span><input aria-label="Cartoon thickness" type="range" min="0.3" max="1.3" step="0.05" value={projection.representationState.parameters.cartoonThickness} onChange={(event) => onRepresentationSettings({ cartoonThickness: Number(event.target.value) })} /></label></div></details>
          <details><summary>Advanced</summary><div className="details-body"><div className="display-capability">Clipping · {projection.camera.clippingMode.toUpperCase()}</div><label className="display-range"><span>FOV <output>{projection.camera.fov.toFixed(0)}°</output></span><input aria-label="Camera FOV" type="range" min="5" max="90" step="1" value={projection.camera.fov} onChange={(event) => onCameraSettings({ fov: Number(event.target.value) })} /></label><label className="display-range"><span>Near clip <output>{numberValue(projection.camera.nearClip)}</output></span><input aria-label="Near clip" type="number" min="0.01" step="0.01" value={projection.camera.nearClip} onChange={(event) => onCameraSettings({ nearClip: Math.max(0.01, Number(event.target.value)) })} /></label><label className="display-range"><span>Far clip <output>{numberValue(projection.camera.farClip)}</output></span><input aria-label="Far clip" type="number" min="1" step="1" value={projection.camera.farClip} onChange={(event) => onCameraSettings({ farClip: Math.max(projection.camera.nearClip + 1, Number(event.target.value)) })} /></label><button type="button" className="reset-view" onClick={() => onCameraSettings({ clippingMode: "auto" })}>Reset clipping to Auto</button></div></details>
        </div>
      </section>
      <section className="panel-card measurement-card"><div className="panel-heading"><div><span className="eyebrow">INTERACTION</span><h2>Measurements</h2></div><span className="measurement-count">{measurements.length}</span></div><div className="measurement-toolbar"><button className={activeMeasurement("DISTANCE") ? "measurement-button measurement-button--active" : "measurement-button"} onClick={() => onMeasurementMode(activeMeasurement("DISTANCE") ? null : "DISTANCE")} type="button">Distance</button><button className={activeMeasurement("ANGLE") ? "measurement-button measurement-button--active" : "measurement-button"} onClick={() => onMeasurementMode(activeMeasurement("ANGLE") ? null : "ANGLE")} type="button">Angle</button><button className={activeMeasurement("DIHEDRAL") ? "measurement-button measurement-button--active" : "measurement-button"} onClick={() => onMeasurementMode(activeMeasurement("DIHEDRAL") ? null : "DIHEDRAL")} type="button">Dihedral</button></div>{measurementMode && <div className="measurement-hint" role="status">Pick {({ DISTANCE: 2, ANGLE: 3, DIHEDRAL: 4 }[measurementMode])} atoms in order · {measurementSlots.length} picked</div>}{measurements.length > 0 && <div className="measurement-list">{measurements.map((measurement) => <div className="measurement-result" key={measurement.id}><div><strong>{measurement.kind}</strong><span>{formatMeasurement(measurement)}</span></div><div className="measurement-actions"><button type="button" onClick={() => onMeasurementVisibility(measurement.id, !measurement.presentation.visible)}>{measurement.presentation.visible ? "Hide" : "Show"}</button><button type="button" onClick={() => onMeasurementDelete(measurement.id)}>Delete</button></div></div>)}</div>}{measurementMode && <button className="reset-view" type="button" onClick={onMeasurementClear}>Clear picks</button>}</section>
    </aside>
  );
};
