import type { CanonicalMolecularStructure, CapabilityState } from "@molecular/contracts";

export type SurfaceKind = "VDW" | "SAS" | "SES";
export type SurfaceProfile = {
  profile_id: string;
  surface_kind: SurfaceKind;
  radius_source: "canonical_element_vdw_radius";
  probe_radius: number;
  coordinate_state: "active";
  target_atoms: "style_target_atoms";
  contributor_atoms: "target_plus_explicit_occluders";
  occluders: "canonical_coordinate_atoms";
  resolution: number;
  quality: "preview" | "standard" | "high";
  generator: "3dmol-native" | "mole-explorer-native";
  cache_key: string;
  color_source: "atom_color_state";
};

export const SURFACE_PROFILES: Record<SurfaceKind, SurfaceProfile> = {
  VDW: { profile_id: "surface.vdw.element-vdw.v1", surface_kind: "VDW", radius_source: "canonical_element_vdw_radius", probe_radius: 0, coordinate_state: "active", target_atoms: "style_target_atoms", contributor_atoms: "target_plus_explicit_occluders", occluders: "canonical_coordinate_atoms", resolution: 0.5, quality: "standard", generator: "3dmol-native", cache_key: "scientificHash:coordinateState:surface.vdw.element-vdw.v1", color_source: "atom_color_state" },
  SAS: { profile_id: "surface.sas.element-vdw.probe-1.4A.v1", surface_kind: "SAS", radius_source: "canonical_element_vdw_radius", probe_radius: 1.4, coordinate_state: "active", target_atoms: "style_target_atoms", contributor_atoms: "target_plus_explicit_occluders", occluders: "canonical_coordinate_atoms", resolution: 0.5, quality: "standard", generator: "3dmol-native", cache_key: "scientificHash:coordinateState:surface.sas.element-vdw.probe-1.4A.v1", color_source: "atom_color_state" },
  SES: { profile_id: "surface.ses.element-vdw.probe-1.4A.v1", surface_kind: "SES", radius_source: "canonical_element_vdw_radius", probe_radius: 1.4, coordinate_state: "active", target_atoms: "style_target_atoms", contributor_atoms: "target_plus_explicit_occluders", occluders: "canonical_coordinate_atoms", resolution: 0.5, quality: "standard", generator: "3dmol-native", cache_key: "scientificHash:coordinateState:surface.ses.element-vdw.probe-1.4A.v1", color_source: "atom_color_state" },
};

export type StyleProfileId = "line" | "stick" | "ball-and-stick" | "space-filling" | "van-der-waals-surface" | "solvent-accessible-surface" | "solvent-excluded-surface" | "mesh" | "dots" | "dot-surface" | "cartoon" | "ribbon" | "trace" | "putty" | "nonbonded-crosses" | "nonbonded-spheres" | "licorice";
export type RepresentationCapabilityStatus = "IMPLEMENTED" | "IMPLEMENTED_WITH_LIMITATIONS" | "INSUFFICIENT_DATA" | "VALID_EMPTY" | "NOT_IMPLEMENTED" | "PROFILE_GATED";
export type RepresentationTarget = "protein" | "ligand" | "water" | "ions" | "other";
export type CanonicalRepresentation = "LINES" | "STICKS" | "SPHERES" | "CARTOON" | "RIBBON" | "NONBONDED" | "NB_SPHERES" | "SURFACE" | "MESH" | "DOTS";
export type StyleDefinition = {
  id: StyleProfileId; label: string; actionId: string; capability: CapabilityState; status: RepresentationCapabilityStatus; profile: string; preconditions: string; rendererProjection: string; canonicalRepresentation: CanonicalRepresentation; eligibleTargetTypes: readonly RepresentationTarget[]; rendererSupport: boolean; canonicalSupport: boolean; requiredScientificData: readonly string[]; knownLimitations: readonly string[]; maySelect: boolean; conformanceStatus: "MOLEXPLORER_NATIVE" | "UNVERIFIED_PYMOL_CONFORMANCE"; unsupportedReason?: string;
};

const ATOM_TARGETS: readonly RepresentationTarget[] = ["protein", "ligand", "water", "ions", "other"];
const POLYMER_TARGETS: readonly RepresentationTarget[] = ["protein"];
const native = "MOLEXPLORER_NATIVE" as const;
const unverified = "UNVERIFIED_PYMOL_CONFORMANCE" as const;
const limitedSurface = (id: StyleProfileId, label: string, actionId: string, profile: string, projection: string, requirements: string[], limitations: string[], canonicalRepresentation: CanonicalRepresentation): StyleDefinition => ({ id, label, actionId, capability: "SUPPORTED_WITH_LIMITATIONS", status: "IMPLEMENTED_WITH_LIMITATIONS", profile, preconditions: requirements.join(", "), rendererProjection: projection, canonicalRepresentation, eligibleTargetTypes: ATOM_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: requirements, knownLimitations: limitations, maySelect: true, conformanceStatus: canonicalRepresentation === "DOTS" ? native : unverified });

export const STYLE_DEFINITIONS: readonly StyleDefinition[] = [
  { id: "line", label: "Line", actionId: "REPRESENTATION.APPLY_LINE", capability: "SUPPORTED", status: "IMPLEMENTED", profile: "canonical-bond-lines.v1", preconditions: "CanonicalBond endpoints and active coordinates", rendererProjection: "3Dmol line style over canonical bond adjacency", canonicalRepresentation: "LINES", eligibleTargetTypes: ATOM_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: ["CanonicalBond", "coordinates"], knownLimitations: ["Only authoritative bonds are drawn."], maySelect: true, conformanceStatus: native },
  { id: "stick", label: "Stick", actionId: "REPRESENTATION.APPLY_STICK", capability: "SUPPORTED", status: "IMPLEMENTED", profile: "canonical-bond-sticks.v1", preconditions: "CanonicalBond endpoints and active coordinates", rendererProjection: "3Dmol capped cylinders over canonical bond adjacency", canonicalRepresentation: "STICKS", eligibleTargetTypes: ATOM_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: ["CanonicalBond", "coordinates"], knownLimitations: ["Only authoritative bonds are drawn."], maySelect: true, conformanceStatus: native },
  { id: "ball-and-stick", label: "Ball-and-Stick", actionId: "REPRESENTATION.APPLY_BALL_AND_STICK", capability: "SUPPORTED", status: "IMPLEMENTED", profile: "canonical-stick-plus-small-sphere.v1", preconditions: "Canonical coordinates and canonical bonds", rendererProjection: "Canonical sticks plus presentation-scale spheres", canonicalRepresentation: "STICKS", eligibleTargetTypes: ATOM_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: ["coordinates", "CanonicalBond", "element"], knownLimitations: ["Sphere radius is a presentation parameter."], maySelect: true, conformanceStatus: native },
  { id: "space-filling", label: "Space-Filling", actionId: "REPRESENTATION.APPLY_SPACE_FILLING", capability: "SUPPORTED", status: "IMPLEMENTED", profile: "canonical-element-vdw-full-radius.v1", preconditions: "Canonical atom coordinates and element identity", rendererProjection: "Atom-centered full-radius spheres", canonicalRepresentation: "SPHERES", eligibleTargetTypes: ATOM_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: ["coordinates", "element"], knownLimitations: ["This is atom-centered space filling, not a molecular surface."], maySelect: true, conformanceStatus: native },
  limitedSurface("van-der-waals-surface", "Van der Waals Surface", "REPRESENTATION.APPLY_VDW_SURFACE", SURFACE_PROFILES.VDW.profile_id, "3Dmol VDW surface behind the adapter", ["VDW radii", "surface profile"], ["Surface generation is delegated to 3Dmol; exact PyMOL surface equivalence is unverified."], "SURFACE"),
  limitedSurface("solvent-accessible-surface", "Solvent-Accessible Surface", "REPRESENTATION.APPLY_SAS", SURFACE_PROFILES.SAS.profile_id, "3Dmol SAS surface behind the adapter", ["VDW radii", "1.4 Å probe", "surface profile"], ["This is a render projection; quantitative SASA is not a scientific result."], "SURFACE"),
  limitedSurface("solvent-excluded-surface", "Solvent-Excluded Surface", "REPRESENTATION.APPLY_SES", SURFACE_PROFILES.SES.profile_id, "3Dmol SES surface behind the adapter", ["VDW radii", "1.4 Å probe", "surface profile"], ["This is a render projection; quantitative surface area is not a scientific result."], "SURFACE"),
  { id: "mesh", label: "Mesh", actionId: "REPRESENTATION.APPLY_MESH", capability: "SUPPORTED_WITH_LIMITATIONS", status: "IMPLEMENTED_WITH_LIMITATIONS", profile: "surface-mesh.v2", preconditions: "Canonical VDW surface samples and mesh width", rendererProjection: "Application-native exposed VDW sample points joined as a visible wire/lattice network", canonicalRepresentation: "MESH", eligibleTargetTypes: ATOM_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: ["surface profile", "mesh width"], knownLimitations: ["Mesh is a deterministic presentation lattice, not a quantitative mesh or separate scientific surface."], maySelect: true, conformanceStatus: native },
  { id: "dots", label: "Dots", actionId: "REPRESENTATION.APPLY_DOTS", capability: "SUPPORTED_WITH_LIMITATIONS", status: "IMPLEMENTED_WITH_LIMITATIONS", profile: "surface-dots.v1", preconditions: "Canonical coordinates and deterministic sampling", rendererProjection: "Application-native exposed surface points", canonicalRepresentation: "DOTS", eligibleTargetTypes: ATOM_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: ["surface profile", "dot sampling profile"], knownLimitations: ["Dots are deterministic presentation sampling, not a quantitative area result."], maySelect: true, conformanceStatus: native },
  { id: "dot-surface", label: "Dot Surface", actionId: "REPRESENTATION.APPLY_DOT_SURFACE", capability: "SUPPORTED_WITH_LIMITATIONS", status: "IMPLEMENTED_WITH_LIMITATIONS", profile: "surface-dot-surface.v1", preconditions: "Canonical coordinates and deterministic surface sampling", rendererProjection: "Application-native exposed SES-like points", canonicalRepresentation: "DOTS", eligibleTargetTypes: ATOM_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: ["surface profile", "dot-surface generator"], knownLimitations: ["Dot Surface is Mole Explorer native and not an exact PyMOL token."], maySelect: true, conformanceStatus: native },
  { id: "cartoon", label: "Cartoon", actionId: "REPRESENTATION.APPLY_CARTOON", capability: "SUPPORTED_WITH_LIMITATIONS", status: "IMPLEMENTED_WITH_LIMITATIONS", profile: "canonical-polymer-cartoon.v1", preconditions: "Canonical polymer hierarchy and active coordinates", rendererProjection: "3Dmol cartoon over canonical polymer targets", canonicalRepresentation: "CARTOON", eligibleTargetTypes: POLYMER_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: ["polymer hierarchy", "coordinates"], knownLimitations: ["Exact PyMOL conformance is unverified."], maySelect: true, conformanceStatus: unverified },
  { id: "ribbon", label: "Ribbon", actionId: "REPRESENTATION.APPLY_RIBBON_STYLE", capability: "SUPPORTED_WITH_LIMITATIONS", status: "IMPLEMENTED_WITH_LIMITATIONS", profile: "canonical-polymer-ribbon-oval.v1", preconditions: "Canonical polymer hierarchy/order and active coordinates", rendererProjection: "3Dmol oval ribbon path behind the adapter", canonicalRepresentation: "RIBBON", eligibleTargetTypes: POLYMER_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: ["polymer hierarchy", "coordinates"], knownLimitations: ["Exact PyMOL ribbon conformance is unverified; renderer-native oval geometry is explicit and distinct from Cartoon."], maySelect: true, conformanceStatus: unverified },
  { id: "trace", label: "Trace", actionId: "REPRESENTATION.APPLY_TRACE", capability: "SUPPORTED_WITH_LIMITATIONS", status: "IMPLEMENTED_WITH_LIMITATIONS", profile: "canonical-polymer-trace.v1", preconditions: "Canonical polymer hierarchy/backbone and active coordinates", rendererProjection: "3Dmol trace cylinders over canonical backbone", canonicalRepresentation: "CARTOON", eligibleTargetTypes: POLYMER_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: ["polymer hierarchy", "backbone coordinates"], knownLimitations: ["Exact PyMOL conformance is unverified."], maySelect: true, conformanceStatus: unverified },
  { id: "putty", label: "Putty", actionId: "REPRESENTATION.APPLY_PUTTY", capability: "SUPPORTED_WITH_LIMITATIONS", status: "IMPLEMENTED_WITH_LIMITATIONS", profile: "canonical-polymer-putty-bfactor.v1", preconditions: "Canonical polymer hierarchy and source B-factor values", rendererProjection: "Variable-radius canonical trace by residue B-factor", canonicalRepresentation: "CARTOON", eligibleTargetTypes: POLYMER_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: ["polymer hierarchy", "source B-factor values"], knownLimitations: ["No fabricated B-factor is supplied; exact PyMOL conformance is unverified."], maySelect: true, conformanceStatus: unverified },
  { id: "nonbonded-crosses", label: "Non-bonded (crosses)", actionId: "REPRESENTATION.APPLY_NONBONDED_CROSSES", capability: "SUPPORTED_WITH_LIMITATIONS", status: "IMPLEMENTED_WITH_LIMITATIONS", profile: "canonical-zero-bond-crosses.v1", preconditions: "Canonical topology identifies zero bonded neighbors", rendererProjection: "Crosses on coordinate-present zero-bond atoms", canonicalRepresentation: "NONBONDED", eligibleTargetTypes: ATOM_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: ["canonical topology", "coordinates"], knownLimitations: ["Low or zero eligibility is valid."], maySelect: true, conformanceStatus: native },
  { id: "nonbonded-spheres", label: "Non-bonded (spheres)", actionId: "REPRESENTATION.APPLY_NONBONDED_SPHERES", capability: "SUPPORTED_WITH_LIMITATIONS", status: "IMPLEMENTED_WITH_LIMITATIONS", profile: "canonical-zero-bond-spheres.v1", preconditions: "Canonical topology identifies zero bonded neighbors", rendererProjection: "Small spheres on coordinate-present zero-bond atoms", canonicalRepresentation: "NB_SPHERES", eligibleTargetTypes: ATOM_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: ["canonical topology", "coordinates"], knownLimitations: ["Low or zero eligibility is valid."], maySelect: true, conformanceStatus: native },
  { id: "licorice", label: "Licorice", actionId: "REPRESENTATION.APPLY_LICORICE", capability: "SUPPORTED_WITH_LIMITATIONS", status: "IMPLEMENTED_WITH_LIMITATIONS", profile: "canonical-stick-plus-nb-sphere.v1", preconditions: "Canonical bonds and zero-bond atom topology", rendererProjection: "3Dmol sticks plus non-bonded spheres", canonicalRepresentation: "STICKS", eligibleTargetTypes: ATOM_TARGETS, rendererSupport: true, canonicalSupport: true, requiredScientificData: ["canonical topology", "coordinates"], knownLimitations: ["Non-bonded contribution may be sparse by definition."], maySelect: true, conformanceStatus: native },
];

const normalizeStyleId = (id: string): StyleProfileId => id === "lines" ? "line" : id === "sticks" ? "stick" : id as StyleProfileId;
export const styleDefinition = (id: string): StyleDefinition => STYLE_DEFINITIONS.find((definition) => definition.id === normalizeStyleId(id)) ?? STYLE_DEFINITIONS[0];
export const styleLabel = (id: StyleProfileId | string): string => styleDefinition(id).label;
export const surfaceProfileForStyle = (id: StyleProfileId | string): SurfaceProfile | null => normalizeStyleId(id) === "van-der-waals-surface" ? SURFACE_PROFILES.VDW : normalizeStyleId(id) === "solvent-accessible-surface" ? SURFACE_PROFILES.SAS : normalizeStyleId(id) === "solvent-excluded-surface" ? SURFACE_PROFILES.SES : null;

export type ResolvedRepresentationCapability = StyleDefinition & { eligibleAtomCount: number | null; diagnostic?: string };
export const representationCapabilityFor = (style: string, structure: CanonicalMolecularStructure | null = null): ResolvedRepresentationCapability => {
  const definition = styleDefinition(style);
  if (definition.id === "putty" && structure && !structure.atoms.some((atom) => atom.isPolymer && atom.bFactor !== undefined && atom.bFactor !== null)) return { ...definition, status: "INSUFFICIENT_DATA", capability: "UNAVAILABLE", maySelect: false, eligibleAtomCount: structure.atoms.filter((atom) => atom.isPolymer).length, diagnostic: "Putty unavailable: canonical source B-factor values are required." };
  if (definition.id === "nonbonded-crosses" || definition.id === "nonbonded-spheres") {
    const bondedIds = new Set(structure?.bonds.flatMap((bond) => [bond.atom1, bond.atom2]) ?? []);
    const eligibleAtomCount = structure ? structure.atoms.filter((atom) => !bondedIds.has(atom.stableId)).length : null;
    if (eligibleAtomCount === 0) return { ...definition, status: "VALID_EMPTY", eligibleAtomCount, diagnostic: "Valid empty result: 0 eligible non-bonded atoms in this structure." };
    return { ...definition, eligibleAtomCount };
  }
  return { ...definition, eligibleAtomCount: structure ? structure.atoms.length : null };
};
export const representationCapabilitiesForTarget = (target: RepresentationTarget, structure: CanonicalMolecularStructure | null = null): ResolvedRepresentationCapability[] => STYLE_DEFINITIONS.filter((definition) => definition.eligibleTargetTypes.includes(target)).map((definition) => representationCapabilityFor(definition.id, structure));
export const representationStyleForCommand = (representation: string): StyleProfileId | null => ({ LINES: "line", STICKS: "stick", SPHERES: "space-filling", CARTOON: "cartoon", RIBBON: "ribbon", NONBONDED: "nonbonded-crosses", NB_SPHERES: "nonbonded-spheres", BALL_AND_STICK: "ball-and-stick", SURFACE: "van-der-waals-surface", MESH: "mesh", DOTS: "dots" }[representation] as StyleProfileId | undefined) ?? null;
