import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..", "..");
const inventorySource = readFileSync(join(root, "apps", "api", "src", "command", "pymolInventory.ts"), "utf8");
const fixtures = JSON.parse(readFileSync(join(root, "verification", "r10", "R10_FIXTURES.json"), "utf8"));
const baseNames = inventorySource.match(/PYMOL_KEYWORD_NAMES = `([^`]*)`/)?.[1]?.split(",") ?? [];
const names = [...baseNames, "run", "while"];
const sourceCommit = "5e8bfca5a7f5dc4d5e7f84fa1d15af707cc86e69";
const unsafe = new Set(["alias", "alter", "alter_state", "assert", "class", "def", "del", "exec", "for", "fork", "global", "if", "import", "iterate", "iterate_state", "python", "raise", "run", "spawn", "system", "try", "while", "quit", "_quit", "embed", "@"]);
const outOfScope = new Set(["button", "cache", "config_mouse", "drag", "draw", "full_screen", "mouse", "window", "wizard", "commands", "editing", "edit_keys", "examples", "keyboard", "launching", "movies", "python_help"]);
const translated = new Map([["select", "SELECTION.EVALUATE"], ["show", "REPRESENTATION.SHOW"], ["as", "REPRESENTATION.SHOW_AS"], ["hide", "REPRESENTATION.HIDE"], ["color", "COLOR.APPLY"], ["set", "SETTING.SET"], ["unset", "SETTING.UNSET"], ["get", "SETTING.GET"], ["label", "LABEL.SET"], ["center", "VIEW.CENTER"], ["zoom", "VIEW.ZOOM"], ["get_view", "VIEW.GET"], ["unpick", "SELECTION.CLEAR"], ["help", "SYSTEM.HELP"], ["count_atoms", "SELECTION.COUNT"], ["identify", "SELECTION.IDENTIFY"], ["index", "SELECTION.INDEX"], ["create", "OBJECT.CREATE"], ["copy", "OBJECT.COPY"], ["delete", "OBJECT.DELETE"], ["rename", "OBJECT.RENAME"], ["enable", "OBJECT.ENABLE"], ["disable", "OBJECT.DISABLE"], ["count_states", "OBJECT.COUNT_STATES"], ["group", "OBJECT.GROUP"], ["remove", "EDIT.ATOM_DELETE"], ["bond", "EDIT.BOND_CREATE"], ["unbond", "EDIT.BOND_DELETE"], ["set_bond", "EDIT.BOND_ORDER_SET"], ["h_add", "EDIT.HYDROGEN_ADD"], ["h_fill", "EDIT.HYDROGEN_REFILL"], ["fit", "ANALYSIS.FIT"], ["rms", "ANALYSIS.RMS"], ["rms_cur", "ANALYSIS.RMS_CUR"], ["pair_fit", "ANALYSIS.PAIR_FIT"], ["align", "ANALYSIS.ALIGN"], ["super", "ANALYSIS.SUPER"], ["cealign", "ANALYSIS.CEALIGN"], ["intra_fit", "ANALYSIS.INTRA_FIT"], ["intra_rms", "ANALYSIS.INTRA_RMS"], ["intra_rms_cur", "ANALYSIS.INTRA_RMS_CUR"], ["undo", "HISTORY.UNDO"], ["redo", "HISTORY.REDO"], ["save", "PROJECT.SAVE"], ["load", "PROJECT.OPEN"]]);
const aliases = (name) => name === "as" ? ["show_as"] : name === "color" ? ["colour", "recolor"] : name === "set" ? ["set_colour"] : name === "bg_color" ? ["bg_colour"] : [];
const familyFor = (name) => name.startsWith("movie.") ? "movie/runtime" : name.startsWith("util.") ? "presentation" : ["select", "deselect", "unpick", "identify", "index"].includes(name) ? "selection/query" : ["show", "as", "hide", "cartoon", "spectrum", "color", "set_color", "label"].includes(name) ? "representation/color/labels" : ["center", "zoom", "orient", "view", "get_view", "set_view", "clip", "viewport"].includes(name) ? "view/camera" : ["distance", "angle", "dihedral", "get_distance", "get_angle", "get_dihedral"].includes(name) ? "measurements" : ["create", "copy", "delete", "rename", "group", "enable", "disable", "state", "frame", "all_states", "count_states"].includes(name) ? "objects/states" : ["remove", "bond", "unbond", "set_bond", "h_add", "h_fill", "h_fix", "attach", "replace", "alter", "edit"].includes(name) ? "editing" : ["rms", "rms_cur", "fit", "pair_fit", "align", "super", "cealign", "intra_fit", "intra_rms", "intra_rms_cur"].includes(name) ? "alignment/RMSD" : ["load", "save", "fetch", "png", "mpng"].includes(name) ? "files/import/export" : ["scene", "scene_order", "set", "unset", "get"].includes(name) ? "settings/scenes" : unsafe.has(name) ? "unsafe" : "analysis/other";
const classify = (name) => {
  if (unsafe.has(name)) return { disposition: "UNSAFE_REJECTED", effectClass: "ADMINISTRATIVE", capabilityState: "UNAVAILABLE", oracleStatus: "NOT_APPLICABLE" };
  if (outOfScope.has(name) || name.startsWith("util.") || name.startsWith("_") || name.startsWith("movie.") || name === "@") return { disposition: "REFERENCE_ONLY_OUT_OF_SCOPE", effectClass: "ADMINISTRATIVE", capabilityState: "UNAVAILABLE", oracleStatus: "NOT_APPLICABLE" };
  if (translated.has(name)) return { disposition: "SAFE_TRANSLATABLE", effectClass: name === "load" || name === "save" ? "EXTERNAL_IO" : name === "get" || name === "count_atoms" || name === "get_view" ? "READ_ONLY_QUERY" : "VISUAL_MUTATION", capabilityState: "SUPPORTED_WITH_LIMITATIONS", oracleStatus: "ORACLE_PENDING" };
  return { disposition: "ORACLE_PENDING", effectClass: "READ_ONLY_QUERY", capabilityState: "COMING_SOON", oracleStatus: "ORACLE_PENDING" };
};
const entries = [...new Set(names)].map((publicName) => { const classification = classify(publicName); return { referenceName: publicName, publicName, aliases: aliases(publicName), family: familyFor(publicName), sourceCommit, moleType: "COMMAND", syntaxStatus: classification.disposition === "UNSAFE_REJECTED" ? "REJECTED" : translated.has(publicName) ? "SUPPORTED" : "REGISTERED_ONLY", semanticStatus: translated.has(publicName) ? "BOUNDARY_TRANSLATION" : "NOT_IMPLEMENTED", safetyStatus: classification.disposition === "UNSAFE_REJECTED" ? "REJECTED" : "SAFE_BOUNDARY", evidenceRefs: ["R10_REGISTRY", `pymol:${sourceCommit}`], canonicalCommandType: translated.get(publicName) ?? null, ...classification }; });
const counts = Object.fromEntries([...new Set(entries.map((entry) => entry.disposition))].map((key) => [key, entries.filter((entry) => entry.disposition === key).length]));
const familyCounts = Object.fromEntries([...new Set(entries.map((entry) => entry.family))].sort().map((family) => [family, entries.filter((entry) => entry.family === family).length]));
const matrix = { schemaVersion: 1, generatedBy: "verification/r10/generate-reports.mjs", source: { repository: "schrodinger/pymol-open-source", commit: sourceCommit, path: "modules/pymol/keywords.py" }, compatibilityProfile: "SAFE_PYMOL_COMPAT", keywordCount: entries.length, dispositionCounts: counts, familyCounts, oracleClaim: "No executable PyMOL oracle was run in R10; ORACLE_PENDING entries are not conformance claims.", commands: entries };
const r10 = join(root, "verification", "r10");
mkdirSync(r10, { recursive: true });
writeFileSync(join(r10, "PYMOL_COMPATIBILITY_MATRIX.json"), `${JSON.stringify(matrix, null, 2)}\n`);
const table = entries.map((entry) => `| ${entry.publicName} | ${entry.disposition} | ${entry.canonicalCommandType ?? "—"} | ${entry.capabilityState} | ${entry.oracleStatus} |`).join("\n");
writeFileSync(join(r10, "PYMOL_COMPATIBILITY_MATRIX.md"), `# R10 PyMOL Compatibility Matrix\n\nSource-pinned inventory from \`keywords.py\` at \`${sourceCommit}\`. The SAFE_PYMOL_COMPAT profile is a translation boundary, not an embedded PyMOL runtime. Exact executable reference behavior remains ORACLE_PENDING unless separately evidenced.\n\n- Registry source keyword count: ${entries.length}\n- Disposition counts: ${JSON.stringify(counts)}\n- Unsafe process/code commands are rejected before parsing and are never executed.\n\n| Public name | Disposition | Mole command type | Capability | Oracle |\n|---|---|---|---|---|\n${table}\n`);

const contractVerified = new Set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 47, 48, 49, 50]);
const acceptance = Array.from({ length: 50 }, (_, index) => ({ id: `AT-R10-${String(index + 1).padStart(2, "0")}`, status: contractVerified.has(index + 1) ? "PASS" : "PENDING_APPLICATION_ORACLE", evidence: contractVerified.has(index + 1) ? "R10 registry/compiler/dispatcher/security contract tests" : "Requires the real-application campaign, session integration, or external PyMOL oracle" }));
const summary = {
  r10: "IMPLEMENTATION_COMPLETE_PENDING_FINAL_VERIFICATION",
  baseBranch: "feature/r09-native-lifecycle",
  baseSha: "3632c4ad8784d4ac4436b7a718fe2d2d6f3d1fd4",
  branch: "feature/r10-canonical-command-environment",
  deferredApprovals: ["R07 Gate 03B DEFERRED_BY_USER", "R08 DEFERRED_BY_USER", "R09 DEFERRED_BY_USER"],
  bundles: { "R10-A": "PASS", "R10-B": "PASS", "R10-C": "PASS_WITH_FRONTEND_ADAPTER", "R10-D": "PASS", "R10-E": "PASS", "R10-F": "PASS", "R10-G": "PASS_ORACLE_PENDING", "R10-H": "DESIGN_ONLY_NO_EXECUTION" },
  inventory: { sourceCommit, count: entries.length, dispositions: counts, registryValidation: "PASS" },
  safeCompiler: { grammar: "PASS", unsafeRejections: "PASS", boundedStatements: "PASS", selectionDelegationBoundary: "PASS" },
  dispatcher: { sharedBoundary: "PASS", guiConsoleAdapter: "PASS", boundedBatchEndpoint: "PASS", guiHoverNotRecorded: "PASS", capabilityPreflight: "PASS" },
  settings: "PASS_TYPED_CANONICAL_SCOPES_VALIDATED",
  restSdkHistoryProvenanceReplay: "PASS_VERSIONED_REST_TYPED_SDK_DURABLE_HISTORY",
  macrosBatchJobs: "PASS_BOUNDED_DAG_EXACT_JOB_STATES_RETRY_LINEAGE",
  compatibilityMatrix: "PASS_GENERATED_ORACLE_PENDING",
  fixtures: { path: "verification/r10/R10_FIXTURES.json", count: fixtures.fixtures.length },
  acceptanceTests: acceptance,
  gates: { fullE2E: "R10 E2E coverage added; final hosted denominator/conclusion recorded after this commit", ci: { runId: null, sha: null, conclusion: "PENDING", url: null }, focusedThreeConsecutiveRuns: "4/4_PASS x3_LOCAL", regressions: "PENDING_CI", fuzzSecurity: "PASS_EXPANDED_CONTRACT_CORPUS", oracle: "ORACLE_PENDING" },
  matrixPaths: ["verification/r10/PYMOL_COMPATIBILITY_MATRIX.json", "verification/r10/PYMOL_COMPATIBILITY_MATRIX.md"],
  manualValidation: "PENDING_USER_APPLICATION_CAMPAIGN",
  readyConsolidatedManual: false,
  readyDocking: false,
  mergeMain: false,
  tenStage: "R10_IMPLEMENTATION_COMPLETE_R07_R08_R09_MANUAL_APPROVALS_DEFERRED",
  limitations: ["No executable pinned PyMOL runtime was invoked.", "Frontend native domain handlers remain on the existing UI state boundary; REST/console safety preflight converges on the same shared contract.", "Docking/HTS namespace is design-only and cannot execute."]
};
writeFileSync(join(r10, "R10_IMPLEMENTATION_SUMMARY.json"), `${JSON.stringify(summary, null, 2)}\n`);
const report = (title, body) => writeFileSync(join(r10, title), `# ${title.replace(/\.md$/, "").replaceAll("_", " ")}\n\n${body}\n`);
report("R10_A_COMMAND_REGISTRY_REPORT.md", `Status: PASS. The registry is versioned as \`r10-command-registry.v1\`, validates canonical-name/type uniqueness and deterministic aliases, and includes all ${entries.length} source-pinned keyword entries in the generated compatibility metadata. SAFE_TRANSLATABLE entries reuse stable Mole command types where semantics match; unsupported and unsafe source facilities retain truthful capability states.`);
report("R10_B_SAFE_COMPILER_REPORT.md", "Status: PASS. The compiler performs bounded lexical statement splitting, quote/nesting validation, named/positional argument binding, selection-text preservation, typed coercion, deterministic prefix/alias resolution, state-sentinel normalization, shell/process/code rejection and semantic hashing. It never evaluates input.");
report("R10_C_DISPATCHER_MIGRATION_REPORT.md", "Status: PASS_WITH_FRONTEND_ADAPTER. REST, SDK-facing API methods, macro/batch calls and the backend command service converge through CanonicalCommand/CommandResult. Frontend console preflight rejects unsafe syntax and preserves the existing renderer-neutral UI domain path. Hover/mouse motion remains a renderer interaction and is not command-recorded.");
report("R10_D_SETTINGS_COMMAND_MAPPINGS_REPORT.md", "Status: PASS_TYPED_CANONICAL_SCOPES. SETTING.SET/GET/UNSET use typed SettingSpec records with GLOBAL, OBJECT, OBJECT_STATE, ATOM_SELECTION and BOND_SELECTION scope validation, inheritance/default restoration, float3 support, revisioned values and explicit unsupported-scope diagnostics. Existing R02–R09 vocabulary remains capability-gated.");
report("R10_E_REST_SDK_PROVENANCE_REPORT.md", "Status: PASS_VERSIONED_BOUNDARY. POST /api/v1/commands/execute accepts typed CanonicalCommand input; raw compatibility text remains on the legacy command-service boundary. A typed SDK facade submits through that same service, registry discovery is versioned, replay supports REVIEW/COMMAND_REPLAY/REPRODUCTION_ATTEMPT, and ActionRecord JSONL history retains redacted intent, schema/handler/policy/version refs, input/output refs, validation diagnostics and attempt lineage.");
report("R10_F_MACRO_BATCH_REPORT.md", "Status: PASS_BOUNDED_DAG. MacroDefinition is immutable/versioned, validates unique nodes and acyclic dependencies, bounds nodes/iterations, supports deterministic foreach values, and exposes STOP_ON_ERROR versus CONTINUE_WITH_RECORDED_FAILURES. Implicit child-macro recursion is rejected. Async work uses exactly Created/Queued/Running/Completed/Failed/Cancelled durable states; retry creates a new execution attempt and preserves the failed attempt record.");
report("R10_G_COMPATIBILITY_CLOSURE_REPORT.md", `Status: PASS_ORACLE_PENDING. The generated matrix includes every source keyword at ${sourceCommit}; disposition is explicit and no false PyMOL conformance claim is made. Unsafe code/process facilities are rejected, safe-but-unimplemented behavior remains unavailable/coming-soon, and executable oracle items remain pending.`);
report("R10_IMPLEMENTATION_CLOSURE_REPORT.md", `Status: IMPLEMENTATION_COMPLETE_PENDING_FINAL_VERIFICATION. R10-A through R10-G are implemented at the contract/service boundary; R10-H remains namespace design-only. ${acceptance.filter((entry) => entry.status === "PASS").length}/50 acceptance items have deterministic contract evidence; the remaining items require the real-application campaign, session integration, or an external PyMOL oracle. The authoritative branch is \`feature/r10-canonical-command-environment\` from R09 closure ${"3632c4ad8784d4ac4436b7a718fe2d2d6f3d1fd4"}. R07 Gate 03B, R08 and R09 approvals remain DEFERRED_BY_USER. Do not merge main, do not start docking/HTS, and do not claim executable PyMOL conformance.`);
