import { describe, expect, it } from "vitest";
import type { CanonicalAtom, CanonicalMolecularStructure } from "@molecular/contracts";
import { selectionForStableIds } from "../selection/selectionEngine";
import { buildAlignmentMapping, createDefaultAlignmentRequest, analyzeAlignment, isAlignmentResultStale, createAlignmentObject, getRawAlignment, type RigidTransform } from "./alignment";
import { coordinateContextFor } from "../interaction/picking";

const atom = (id: string, serial: number, coordinate: { x: number; y: number; z: number }, residueNumber = serial): CanonicalAtom => ({ stableId: id, serial, atomName: "CA", element: "C", residueName: "ALA", residueNumber, chain: "A", x: coordinate.x, y: coordinate.y, z: coordinate.z, recordType: "ATOM", isPolymer: true, isLigand: false, isWater: false, isIon: false });
const structureFor = (name: string, atoms: readonly CanonicalAtom[], stateId = "state:1"): CanonicalMolecularStructure => ({ id: name, name, format: "pdb", source: { kind: "LOCAL_FILE", originalFilename: `${name}.pdb`, format: "pdb", sha256: name, byteLength: 1, ingestedAt: "2026-01-01T00:00:00.000Z", parserProfile: "test" }, counts: { atoms: atoms.length, residues: atoms.length, chains: 1, polymerAtoms: atoms.length, ligandAtoms: 0, waterAtoms: 0, ionAtoms: 0, otherAtoms: 0 }, bounds: { min: { x: 0, y: 0, z: 0 }, max: { x: 100, y: 100, z: 100 } }, atoms: [...atoms], bonds: [], hierarchy: { chainIds: ["chain:A"], chains: { "chain:A": { id: "chain:A", name: "A", residueIds: atoms.map((entry) => `chain:A:residue:${entry.residueNumber}:`) } }, residues: Object.fromEntries(atoms.map((entry) => [`chain:A:residue:${entry.residueNumber}:`, { id: `chain:A:residue:${entry.residueNumber}:`, name: entry.residueName, number: entry.residueNumber, chainId: "chain:A", atomIds: [entry.stableId], isPolymer: true }])) }, scientificHash: `${name}:revision`, coordinateStates: [{ id: stateId, ordinal: 1, coordinates: Object.fromEntries(atoms.map((entry) => [entry.stableId, { x: entry.x, y: entry.y, z: entry.z }])), coordinateHash: `${name}:coordinates` }], stateOrder: [stateId] });
const requestFor = (source: CanonicalMolecularStructure, target: CanonicalMolecularStructure, operationKind: "RMS_CUR" | "RMS" | "FIT" = "RMS") => createDefaultAlignmentRequest({ operationKind, sourceObjectId: source.id, targetObjectId: target.id, sourceRevisionId: source.scientificHash, targetRevisionId: target.scientificHash, sourceStructure: source, targetStructure: target, sourceStateId: "state:1", targetStateId: "state:1", sourceSelection: selectionForStableIds(source.atoms.map((entry) => entry.stableId), source), targetSelection: selectionForStableIds(target.atoms.map((entry) => entry.stableId), target), sourceCoordinateContext: coordinateContextFor(source, source.id, "state:1"), targetCoordinateContext: coordinateContextFor(target, target.id, "state:1"), explicitPairs: source.atoms.map((entry, index) => ({ sourceAtomUid: entry.stableId, targetAtomUid: target.atoms[index]!.stableId })) });
const z90: RigidTransform = { rotation: [0, -1, 0, 1, 0, 0, 0, 0, 1], translation: { x: 3, y: -2, z: 1 } };
const apply = (point: { x: number; y: number; z: number }) => ({ x: -point.y + 3, y: point.x - 2, z: point.z + 1 });

describe("R08 fixed correspondence and rigid fitting", () => {
  it("AT-R08-01 computes current RMSD without fitting", () => {
    const source = structureFor("source", [atom("s1", 1, { x: 0, y: 0, z: 0 }), atom("s2", 2, { x: 1, y: 0, z: 0 }), atom("s3", 3, { x: 0, y: 2, z: 0 })]);
    const target = structureFor("target", source.atoms.map((entry) => atom(`t${entry.serial}`, entry.serial, { x: entry.x + 2, y: entry.y, z: entry.z })));
    const request = requestFor(source, target, "RMS_CUR"); const mapping = buildAlignmentMapping(request); expect(mapping.ok).toBe(true); if (!mapping.ok) return;
    const result = analyzeAlignment(request, mapping.value); expect(result.currentRmsd).toBeCloseTo(2, 8); expect(result.evaluationRmsd).toBeCloseTo(2, 8); expect(result.resultDisposition).toBe("VALID"); expect(result.translationVector).toEqual({ x: 0, y: 0, z: 0 });
  });

  it("AT-R08-02/03 recovers a proper column-vector transform", () => {
    const points = [{ x: 0, y: 0, z: 0 }, { x: 1, y: 0, z: 0 }, { x: 0, y: 2, z: 0 }, { x: 0, y: 0, z: 3 }]; const source = structureFor("source", points.map((point, index) => atom(`s${index}`, index + 1, point))); const target = structureFor("target", points.map((point, index) => atom(`t${index}`, index + 1, apply(point)))); const request = requestFor(source, target); const mapping = buildAlignmentMapping(request); expect(mapping.ok).toBe(true); if (!mapping.ok) return;
    const result = analyzeAlignment(request, mapping.value); expect(result.initialFittedRmsd).toBeLessThan(1e-8); expect(result.evaluationRmsd).toBeLessThan(1e-8); expect(result.determinant).toBeCloseTo(1, 8); expect(result.orthogonalityError).toBeLessThan(1e-8); expect(result.transformUniqueness).toBe("UNIQUE"); expect(result.translationVector?.x).toBeCloseTo(z90.translation.x, 8); expect(result.rotationMatrix?.[1]).toBeCloseTo(-1, 8);
  });

  it("AT-R08-05 rejects a mirror as a zero-error reflection", () => {
    const source = structureFor("source", [atom("s1", 1, { x: 0, y: 0, z: 0 }), atom("s2", 2, { x: 1, y: 0, z: 0 }), atom("s3", 3, { x: 0, y: 1, z: 0 }), atom("s4", 4, { x: 0, y: 0, z: 1 })]); const target = structureFor("target", source.atoms.map((entry) => atom(`t${entry.serial}`, entry.serial, { x: -entry.x, y: entry.y, z: entry.z }))); const request = requestFor(source, target); const mapping = buildAlignmentMapping(request); expect(mapping.ok).toBe(true); if (!mapping.ok) return; const result = analyzeAlignment(request, mapping.value); expect(result.determinant).toBeGreaterThan(0.99); expect(result.evaluationRmsd).toBeGreaterThan(0.1);
  });

  it("AT-R08-06..09 reports non-unique and ill-conditioned geometry", () => {
    const one = structureFor("one", [atom("s1", 1, { x: 1, y: 2, z: 3 })]); const oneTarget = structureFor("one-target", [atom("t1", 1, { x: 4, y: 5, z: 6 })]); let request = requestFor(one, oneTarget); let mapping = buildAlignmentMapping(request); expect(mapping.ok).toBe(true); if (!mapping.ok) return; let result = analyzeAlignment(request, mapping.value); expect(result.transformUniqueness).toBe("NON_UNIQUE_TRANSFORM");
    const collinear = structureFor("line", [atom("s1", 1, { x: 0, y: 0, z: 0 }), atom("s2", 2, { x: 1, y: 0, z: 0 }), atom("s3", 3, { x: 2, y: 0, z: 0 })]); const lineTarget = structureFor("line-target", collinear.atoms.map((entry) => atom(`t${entry.serial}`, entry.serial, { x: entry.x + 1, y: 0, z: 0 }))); request = requestFor(collinear, lineTarget); mapping = buildAlignmentMapping(request); expect(mapping.ok).toBe(true); if (!mapping.ok) return; result = analyzeAlignment(request, mapping.value); expect(["DEGENERATE_GEOMETRY", "NON_UNIQUE_TRANSFORM", "ILL_CONDITIONED_FIT"]).toContain(result.transformUniqueness);
  });

  it("AT-R08-10/13 validates explicit identity and remains immutable", () => {
    const source = structureFor("source", [atom("s1", 1, { x: 0, y: 0, z: 0 }), atom("s2", 2, { x: 1, y: 0, z: 0 }), atom("s3", 3, { x: 0, y: 1, z: 0 })]); const target = structureFor("target", [atom("t3", 3, { x: 0, y: 1, z: 0 }), atom("t1", 1, { x: 0, y: 0, z: 0 }), atom("t2", 2, { x: 1, y: 0, z: 0 })]); const request = requestFor(source, target); const mapping = buildAlignmentMapping(request); expect(mapping.ok).toBe(true); if (!mapping.ok) return; expect(mapping.value.pairRecords.map((pair) => pair.targetAtomUid)).toEqual(["t3", "t1", "t2"]); expect(Object.isFrozen(mapping.value)).toBe(true); expect(Object.isFrozen(mapping.value.pairRecords[0])).toBe(true);
  });

  it("AT-R08-17/18 exposes alignment objects and stale dependency detection", () => {
    const source = structureFor("source", [atom("s1", 1, { x: 0, y: 0, z: 0 }), atom("s2", 2, { x: 1, y: 0, z: 0 }), atom("s3", 3, { x: 0, y: 1, z: 0 })]); const target = structureFor("target", source.atoms.map((entry) => atom(`t${entry.serial}`, entry.serial, entry))); const request = requestFor(source, target); const mapping = buildAlignmentMapping(request); expect(mapping.ok).toBe(true); if (!mapping.ok) return; const result = analyzeAlignment(request, mapping.value); expect(isAlignmentResultStale(result, request, mapping.value)).toBe(false); const object = createAlignmentObject(result, mapping.value); expect(getRawAlignment(object)).toHaveLength(3); const changed = { ...request, targetRevisionId: "new-revision" }; expect(isAlignmentResultStale(result, changed, mapping.value)).toBe(true); expect(Object.isFrozen(result)).toBe(true);
  });
});
